### ISSUE TITLE
商品登録し商品詳細ページを閲覧しようとしたらエラー

### ISSUE THREAD

**Issue by mochigoma09** [takuto0607/laravel_umarche#7]
事前に画像管理に画像をアップ
→その画像を込みで新規に商品登録したんだけど画像周りがなんかおかしいんだと思う
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/b2c35fd5-d67b-4427-9ee6-ccd99ccab672">

**Comment by takuto0607** [comment]
対応完了しました。
